import { DatabaseEvent, AwarenessEvent, TaskItem, ActivityLog, EventIdea } from '@/types/database.types';

export const INITIAL_EVENT_IDEAS: EventIdea[] = [
  {
    id: 'idea-1',
    title: 'Silicon Valley AI Founders & Investor Roundtable',
    vendor_name: 'SHACK15 / Ferry Building Tech Lounge',
    vendor_website: 'https://shack15.com',
    time_period: 'October 2026 (During SF Tech Week)',
    notes: 'Inquired with alumni member at SHACK15 for private lounge access. Capacity ~60 people. Need A/V mic for 3 founder lightning talks.',
    description: 'A curated fireside chat and networking circle connecting NYU founders building with generative AI/LLMs with top Bay Area seed & Series A VCs.',
    suggested_region: 'South Bay',
    location_name: 'San Francisco (Ferry Building)',
    submitted_by: 'Leighton Gordon',
    submitted_avatar: 'L&A',
    upvotes: 14,
    upvoters: ['Leighton', 'Janice', 'Adi', 'Tammy', 'Brian'],
    tags: ['Tech & AI', 'Founders', 'Networking', 'Venture Capital'],
    estimated_cost_tier: 'Free',
    status: 'Ready to Plan',
    created_at: '2026-07-28T14:00:00Z',
  },
  {
    id: 'idea-2',
    title: 'Alumni Rooftop Sunset Jazz & Cocktails',
    vendor_name: 'Charmaine’s Rooftop Lounge (Proper Hotel)',
    vendor_website: 'https://properhotel.com/san-francisco/restaurants-bars/charmaines/',
    time_period: 'Fall 2026 (Late September/October)',
    notes: 'Heated rooftop firepit terrace overlooking Market St. Group catering package is ~$35/pp including 2 craft cocktail tickets and charcuterie/empanadas.',
    description: 'Golden hour drinks and light bites on an open-air downtown SF terrace with a live student/alumni jazz quartet.',
    suggested_region: 'SF',
    location_name: 'San Francisco (Mid-Market)',
    submitted_by: 'Janice K.',
    submitted_avatar: 'J',
    upvotes: 9,
    upvoters: ['Janice', 'Adi', 'Tammy'],
    tags: ['Social', 'Live Music', 'Cocktails'],
    estimated_cost_tier: '$$ ($25-$60)',
    status: 'Ready to Plan',
    created_at: '2026-08-01T11:30:00Z',
  },
  {
    id: 'idea-3',
    title: 'Marin Headlands Golden Gate Sunrise Hike',
    vendor_name: 'Equator Coffees Sausalito',
    vendor_website: 'https://equatorcoffees.com',
    time_period: 'November 2026 (Weekend Morning)',
    notes: 'Meet at Hawk Hill trailhead parking at 8:30 AM for a 4-mile loop, then drive down to Equator patio for coffee and sourdough pastries.',
    description: 'Early morning brisk 4-mile scenic loop overlooking the Golden Gate Bridge and Pacific ocean, followed by sourdough pastries and coffee in Sausalito.',
    suggested_region: 'East Bay',
    location_name: 'Marin Headlands & Sausalito',
    submitted_by: 'Adi',
    submitted_avatar: 'A',
    upvotes: 7,
    upvoters: ['Adi', 'Leighton', 'Brian'],
    tags: ['Wellness', 'Outdoors', 'Casual'],
    estimated_cost_tier: 'Free',
    status: 'Under Consideration',
    created_at: '2026-08-03T09:15:00Z',
  },
  {
    id: 'idea-4',
    title: 'Stern Bay Area Private Equity & VC Dinner',
    vendor_name: 'Wayfare Tavern (The Billiards Room)',
    vendor_website: 'https://wayfaretavern.com',
    time_period: 'January 2027 (J.P. Morgan Healthcare/Biotech Week)',
    notes: 'Private 3rd-floor dining room holds up to 24 guests. $1,800 food & beverage minimum. Can sell tickets at $75/person to cover.',
    description: 'Private dining room dinner bringing together Stern MBA alumni and undergraduate finance grads working across Bay Area funds.',
    suggested_region: 'SF',
    location_name: 'San Francisco (FiDi)',
    submitted_by: 'Tammy Chen',
    submitted_avatar: 'T',
    upvotes: 11,
    upvoters: ['Tammy', 'Leighton', 'Janice', 'Adi'],
    tags: ['Finance', 'Stern Alumni', 'Dinner'],
    estimated_cost_tier: '$$$ ($60+)',
    status: 'Under Consideration',
    created_at: '2026-08-05T16:20:00Z',
  },
  {
    id: 'idea-5',
    title: 'Tisch Alumni Indie Short Film Showcase',
    vendor_name: 'Roxie Theater (Mission)',
    vendor_website: 'https://roxie.com',
    time_period: 'Winter 2026 / Early 2027',
    notes: 'Little Roxie screening room holds 49 seats. Rental is $350 for 2 hours on weekday evenings with full DCP projection.',
    description: 'Screening of 4 short films and documentaries directed by Bay Area Tisch alumni, followed by an intimate creator Q&A and wine reception.',
    suggested_region: 'SF',
    location_name: 'San Francisco (Mission District)',
    submitted_by: 'Brian T.',
    submitted_avatar: 'B',
    upvotes: 6,
    upvoters: ['Brian', 'Janice'],
    tags: ['Arts & Film', 'Tisch', 'Culture'],
    estimated_cost_tier: '$ (Under $25)',
    status: 'Draft',
    created_at: '2026-08-08T10:00:00Z',
  },
  {
    id: 'idea-6',
    title: 'Boutique Boba & Board Games Social',
    vendor_name: 'Victory Point Board Game Cafe',
    vendor_website: 'https://victorypointcafe.com',
    time_period: 'Spring 2027 (Weekend Afternoon)',
    notes: 'Over 800 board games in library. Reserve large party table for $10/person cover which includes a drink.',
    description: 'Low-stress weekend afternoon gathering at a local Berkeley tea house with modern board games, welcome pack for recent grads relocated to the Bay.',
    suggested_region: 'East Bay',
    location_name: 'Berkeley (Shattuck Ave)',
    submitted_by: 'Janice K.',
    submitted_avatar: 'J',
    upvotes: 8,
    upvoters: ['Janice', 'Adi', 'Tammy'],
    tags: ['Casual', 'Young Alumni', 'Games'],
    estimated_cost_tier: '$ (Under $25)',
    status: 'Draft',
    created_at: '2026-08-09T13:45:00Z',
  },
];

export const INITIAL_EVENTS: DatabaseEvent[] = [
  {
    id: 'evt-1',
    title: 'Equinox Pilates',
    event_date: '2026-10-03',
    status: 'Submitted',
    location_name: 'San Francisco (Market St)',
    region: 'SF',
    cost_per_person: 15,
    primary_host: 'Leighton Gordon',
    co_hosts: ['Adi', 'Brian T.'],
    notes: 'Morning Pilates stretch session for Bay Area alumni with private studio reservation and smoothies afterwards.',
    workflow_progress_current: 20,
    workflow_progress_total: 15,
    created_at: '2026-07-20T10:00:00Z',
    updated_at: '2026-08-01T12:00:00Z'
  },
  {
    id: 'evt-2',
    title: 'Dolores Park Picnic',
    event_date: '2026-10-08',
    status: 'Planning',
    location_name: 'San Francisco (Mission)',
    region: 'SF',
    cost_per_person: 0,
    primary_host: 'Janice K.',
    co_hosts: ['Leighton Gordon', 'Adi'],
    notes: 'Annual fall outdoor mixer at Mission Dolores Park. Bring blankets, sunblock, and lawn games.',
    workflow_progress_current: 20,
    workflow_progress_total: 14,
    created_at: '2026-07-25T14:00:00Z',
    updated_at: '2026-08-05T09:30:00Z'
  },
  {
    id: 'evt-3',
    title: 'Wine Tasting Napa',
    event_date: '2026-10-19',
    status: 'Planning',
    location_name: 'Napa Valley / SF Pickup',
    region: 'SF',
    cost_per_person: 65,
    primary_host: 'Janice K.',
    co_hosts: ['Tammy Chen'],
    notes: 'Chartered luxury sprinter van from Downtown SF to 2 boutique alumni-owned wineries in Stags Leap.',
    workflow_progress_current: 9,
    workflow_progress_total: 13,
    created_at: '2026-07-15T11:00:00Z',
    updated_at: '2026-07-25T16:45:00Z'
  },
  {
    id: 'evt-4',
    title: 'Quarterly Cafe Meetup',
    event_date: '2026-10-22',
    status: 'Planning',
    location_name: 'San Francisco (SOMA)',
    region: 'SF',
    cost_per_person: 5,
    primary_host: 'Tammy Chen',
    co_hosts: ['Leighton Gordon', 'Adi'],
    notes: 'Casual Thursday morning coffee & tech networking meetup at Sightglass SOMA.',
    workflow_progress_current: 9,
    workflow_progress_total: 13,
    created_at: '2026-07-28T08:00:00Z',
    updated_at: '2026-08-04T15:10:00Z'
  },
  {
    id: 'evt-5',
    title: 'Alumni Volunteer Meeting',
    event_date: '2026-11-15',
    status: 'Planning',
    location_name: 'San Francisco',
    region: 'SF',
    cost_per_person: 0,
    primary_host: 'Tammy Chen',
    co_hosts: ['Brian T.'],
    notes: 'Q4 club committee meeting to review 2027 calendar, volunteer assignments, and campus tie-ins.',
    workflow_progress_current: 0,
    workflow_progress_total: 13,
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-08-01T10:00:00Z'
  },
  {
    id: 'evt-6',
    title: 'Thanksgiving Dinner',
    event_date: '2026-11-26',
    status: 'Idea',
    location_name: 'San Francisco',
    region: 'SF',
    cost_per_person: 45,
    primary_host: 'Janice K.',
    co_hosts: [],
    notes: 'Friendsgiving feast for Bay Area alumni staying in town during Thanksgiving week.',
    workflow_progress_current: 0,
    workflow_progress_total: 10,
    created_at: '2026-08-02T13:00:00Z',
    updated_at: '2026-08-02T13:00:00Z'
  },
  {
    id: 'evt-7',
    title: 'Holiday Party',
    event_date: '2026-12-12',
    status: 'Planning',
    location_name: 'San Francisco (FiDi)',
    region: 'SF',
    cost_per_person: 35,
    primary_host: 'Leighton Gordon',
    co_hosts: ['Adi', 'Janice K.'],
    notes: 'Signature annual Bay Area alumni gala cocktail reception with live jazz and NYU memorabilia raffle.',
    workflow_progress_current: 4,
    workflow_progress_total: 14,
    created_at: '2026-07-10T17:00:00Z',
    updated_at: '2026-08-08T11:20:00Z'
  },
  {
    id: 'evt-8',
    title: 'New Year Mixer',
    event_date: '2027-01-08',
    status: 'Planning',
    location_name: 'San Francisco (Marina)',
    region: 'SF',
    cost_per_person: 15,
    primary_host: 'Janice K.',
    co_hosts: ['Leighton Gordon'],
    notes: 'Kick off 2027 with fellow alumni, new resolution discussions, and welcome new grads relocating to SF.',
    workflow_progress_current: 2,
    workflow_progress_total: 12,
    created_at: '2026-08-05T09:00:00Z',
    updated_at: '2026-08-05T09:00:00Z'
  }
];

export const INITIAL_AWARENESS_EVENTS: AwarenessEvent[] = [
  {
    id: 'awr-1',
    title: 'SF Tech Week Social Event',
    start_date: '2026-10-05',
    end_date: '2026-10-11',
    location: 'San Francisco',
    category: 'Community / Conference',
    is_multi_day: true,
    color_tag: 'emerald',
    notes: 'Massive tech week across SF. High demand for venues, but high density of alumni in town for synergy!'
  },
  {
    id: 'awr-2',
    title: 'SF Tech Week Happy Hour',
    start_date: '2026-10-09',
    end_date: '2026-10-09',
    location: 'San Francisco',
    category: 'Community / Conference',
    is_multi_day: false,
    color_tag: 'emerald',
    notes: 'Community tech happy hour.'
  },
  {
    id: 'awr-3',
    title: 'SOCAP',
    start_date: '2026-10-13',
    end_date: '2026-10-16',
    location: 'San Francisco (Yerba Buena)',
    category: 'Community / Conference',
    is_multi_day: true,
    color_tag: 'emerald',
    notes: 'Social Capital Markets annual conference for impact investing, ESG, and social enterprise leaders.'
  },
  {
    id: 'awr-4',
    title: 'Indigenous Peoples\' Day',
    start_date: '2026-10-12',
    end_date: '2026-10-12',
    location: 'Bay Area / Federal',
    category: 'Civic / Holiday',
    is_multi_day: false,
    color_tag: 'blue',
    notes: 'Long weekend civic holiday.'
  },
  {
    id: 'awr-5',
    title: 'Halloween',
    start_date: '2026-10-31',
    end_date: '2026-10-31',
    location: 'Bay Area',
    category: 'Civic / Holiday',
    is_multi_day: false,
    color_tag: 'amber',
    notes: 'Halloween weekend - avoid scheduling conflicting formal dinners.'
  },
  {
    id: 'awr-6',
    title: 'Christmas',
    start_date: '2026-12-25',
    end_date: '2026-12-25',
    location: 'Global',
    category: 'Civic / Holiday',
    is_multi_day: false,
    color_tag: 'blue',
    notes: 'Winter holiday shutdown.'
  },
  {
    id: 'awr-7',
    title: 'J.P. Morgan Healthcare Conference Jan 11-14',
    start_date: '2027-01-11',
    end_date: '2027-01-14',
    location: 'San Francisco (Union Square)',
    category: 'Community / Conference',
    is_multi_day: true,
    color_tag: 'emerald',
    notes: 'Major global healthcare/biotech conference. High hotel & venue compression in Downtown SF.'
  },
  {
    id: 'awr-8',
    title: 'Lunar New Year',
    start_date: '2027-02-06',
    end_date: '2027-02-06',
    location: 'San Francisco (Chinatown)',
    category: 'Cultural',
    is_multi_day: false,
    color_tag: 'rose',
    notes: 'San Francisco Chinatown festival & parade celebration.'
  },
  {
    id: 'awr-9',
    title: 'Holi',
    start_date: '2027-03-22',
    end_date: '2027-03-22',
    location: 'Bay Area',
    category: 'Cultural',
    is_multi_day: false,
    color_tag: 'purple',
    notes: 'Spring festival of colors.'
  }
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'tsk-1',
    title: 'Submit Dolores Park details (6w warning)',
    assignee: 'Leighton',
    completed: false,
    due_date: '2026-08-27',
    event_id: 'evt-2',
    warning_type: '6w'
  },
  {
    id: 'tsk-2',
    title: 'Follow up on Equinox proposal',
    assignee: 'Leighton',
    completed: false,
    due_date: '2026-08-20',
    event_id: 'evt-1',
    warning_type: 'standard'
  },
  {
    id: 'tsk-3',
    title: 'Draft newsletter copy for Napa trip',
    assignee: 'Leighton',
    completed: false,
    due_date: '2026-09-01',
    event_id: 'evt-3',
    warning_type: 'standard'
  },
  {
    id: 'tsk-4',
    title: 'Draft newsletter tasks details planned',
    assignee: 'Leighton',
    completed: false,
    due_date: '2026-09-10',
    event_id: 'evt-5',
    warning_type: 'standard'
  }
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-1',
    user_name: 'Jan',
    user_avatar_initials: 'J',
    action: 'added new Grad event',
    target: 'Young Alumni Social',
    created_at: '2026-08-10T15:00:00Z',
    relative_time: '1 days ago',
    badge_color: 'bg-emerald-600 text-white'
  },
  {
    id: 'act-2',
    user_name: 'Tammy',
    user_avatar_initials: 'T',
    action: 'updated Wine Tasting Napa status to Planning',
    target: 'Wine Tasting Napa',
    created_at: '2026-07-25T14:30:00Z',
    relative_time: '17 days ago',
    badge_color: 'bg-purple-600 text-white'
  },
  {
    id: 'act-3',
    user_name: 'Adi',
    user_avatar_initials: 'A',
    action: 'edited Quarterly Cafe details',
    target: 'Quarterly Cafe Meetup',
    created_at: '2026-08-04T12:00:00Z',
    relative_time: '7 days ago',
    badge_color: 'bg-purple-600 text-white'
  },
  {
    id: 'act-4',
    user_name: 'Adi',
    user_avatar_initials: 'A',
    action: 'edited Quarterly Cafe details',
    target: 'Quarterly Cafe Meetup',
    created_at: '2026-08-04T11:45:00Z',
    relative_time: '7 days ago',
    badge_color: 'bg-purple-600 text-white'
  },
  {
    id: 'act-5',
    user_name: 'Adi',
    user_avatar_initials: 'A',
    action: 'edited Quarterly Cafe details',
    target: 'Quarterly Cafe Meetup',
    created_at: '2026-08-04T11:30:00Z',
    relative_time: '7 days ago',
    badge_color: 'bg-purple-600 text-white'
  }
];
