import { DatabaseEvent, AwarenessEvent, TaskItem, ActivityLog, EventIdea, ClubLeader, BudgetItem } from '@/types/database.types';

export const INITIAL_EVENT_IDEAS: EventIdea[] = [
  {
    id: 'idea-1',
    title: 'Silicon Valley AI Founders & Investor Roundtable',
    vendor_name: 'SHACK15 / Ferry Building Tech Lounge',
    vendor_website: 'https://shack15.com',
    time_period: 'October 2026 (During SF Tech Week)',
    notes: 'Inquired with alumni member at SHACK15 for private lounge access. Capacity ~60 people. Need A/V mic for 3 founder lightning talks.',
    description: 'A curated fireside chat and networking circle connecting NYU founders building with generative AI/LLMs with top Bay Area seed & Series A VCs.',
    suggested_region: 'South Bay',
    location_name: 'San Francisco (Ferry Building)',
    submitted_by: 'Leighton Gordon',
    submitted_avatar: 'L&A',
    upvotes: 14,
    upvoters: ['Leighton', 'Janice', 'Adi', 'Tammy', 'Brian'],
    tags: ['Tech & AI', 'Founders', 'Networking', 'Venture Capital'],
    estimated_cost_tier: 'Free',
    status: 'Ready to Plan',
    created_at: '2026-07-28T14:00:00Z',
  },
  {
    id: 'idea-2',
    title: 'Alumni Rooftop Sunset Jazz & Cocktails',
    vendor_name: 'Charmaine’s Rooftop Lounge (Proper Hotel)',
    vendor_website: 'https://properhotel.com/san-francisco/restaurants-bars/charmaines/',
    time_period: 'Fall 2026 (Late September/October)',
    notes: 'Heated rooftop firepit terrace overlooking Market St. Group catering package is ~$35/pp including 2 craft cocktail tickets and charcuterie/empanadas.',
    description: 'Golden hour drinks and light bites on an open-air downtown SF terrace with a live student/alumni jazz quartet.',
    suggested_region: 'SF',
    location_name: 'San Francisco (Mid-Market)',
    submitted_by: 'Janice K.',
    submitted_avatar: 'J',
    upvotes: 9,
    upvoters: ['Janice', 'Adi', 'Tammy'],
    tags: ['Social', 'Live Music', 'Cocktails'],
    estimated_cost_tier: '$$ ($25-$60)',
    status: 'Ready to Plan',
    created_at: '2026-08-01T11:30:00Z',
  },
  {
    id: 'idea-3',
    title: 'Marin Headlands Golden Gate Sunrise Hike',
    vendor_name: 'Equator Coffees Sausalito',
    vendor_website: 'https://equatorcoffees.com',
    time_period: 'November 2026 (Weekend Morning)',
    notes: 'Meet at Hawk Hill trailhead parking at 8:30 AM for a 4-mile loop, then drive down to Equator patio for coffee and sourdough pastries.',
    description: 'Early morning brisk 4-mile scenic loop overlooking the Golden Gate Bridge and Pacific ocean, followed by sourdough pastries and coffee in Sausalito.',
    suggested_region: 'East Bay',
    location_name: 'Marin Headlands & Sausalito',
    submitted_by: 'Adi',
    submitted_avatar: 'A',
    upvotes: 7,
    upvoters: ['Adi', 'Leighton', 'Brian'],
    tags: ['Wellness', 'Outdoors', 'Casual'],
    estimated_cost_tier: 'Free',
    status: 'Under Consideration',
    created_at: '2026-08-03T09:15:00Z',
  },
  {
    id: 'idea-4',
    title: 'Stern Bay Area Private Equity & VC Dinner',
    vendor_name: 'Wayfare Tavern (The Billiards Room)',
    vendor_website: 'https://wayfaretavern.com',
    time_period: 'January 2027 (J.P. Morgan Healthcare/Biotech Week)',
    notes: 'Private 3rd-floor dining room holds up to 24 guests. $1,800 food & beverage minimum. Can sell tickets at $75/person to cover.',
    description: 'Private dining room dinner bringing together Stern MBA alumni and undergraduate finance grads working across Bay Area funds.',
    suggested_region: 'SF',
    location_name: 'San Francisco (FiDi)',
    submitted_by: 'Tammy Chen',
    submitted_avatar: 'T',
    upvotes: 11,
    upvoters: ['Tammy', 'Leighton', 'Janice', 'Adi'],
    tags: ['Finance', 'Stern Alumni', 'Dinner'],
    estimated_cost_tier: '$$$ ($60+)',
    status: 'Under Consideration',
    created_at: '2026-08-05T16:20:00Z',
  },
  {
    id: 'idea-5',
    title: 'Tisch Alumni Indie Short Film Showcase',
    vendor_name: 'Roxie Theater (Mission)',
    vendor_website: 'https://roxie.com',
    time_period: 'Winter 2026 / Early 2027',
    notes: 'Little Roxie screening room holds 49 seats. Rental is $350 for 2 hours on weekday evenings with full DCP projection.',
    description: 'Screening of 4 short films and documentaries directed by Bay Area Tisch alumni, followed by an intimate creator Q&A and wine reception.',
    suggested_region: 'SF',
    location_name: 'San Francisco (Mission District)',
    submitted_by: 'Brian T.',
    submitted_avatar: 'B',
    upvotes: 6,
    upvoters: ['Brian', 'Janice'],
    tags: ['Arts & Film', 'Tisch', 'Culture'],
    estimated_cost_tier: '$ (Under $25)',
    status: 'Draft',
    created_at: '2026-08-08T10:00:00Z',
  },
  {
    id: 'idea-6',
    title: 'Boutique Boba & Board Games Social',
    vendor_name: 'Victory Point Board Game Cafe',
    vendor_website: 'https://victorypointcafe.com',
    time_period: 'Spring 2027 (Weekend Afternoon)',
    notes: 'Over 800 board games in library. Reserve large party table for $10/person cover which includes a drink.',
    description: 'Low-stress weekend afternoon gathering at a local Berkeley tea house with modern board games, welcome pack for recent grads relocated to the Bay.',
    suggested_region: 'East Bay',
    location_name: 'Berkeley (Shattuck Ave)',
    submitted_by: 'Janice K.',
    submitted_avatar: 'J',
    upvotes: 8,
    upvoters: ['Janice', 'Adi', 'Tammy'],
    tags: ['Casual', 'Young Alumni', 'Games'],
    estimated_cost_tier: '$ (Under $25)',
    status: 'Draft',
    created_at: '2026-08-09T13:45:00Z',
  },
];

export const INITIAL_EVENTS: DatabaseEvent[] = [
  {
    id: 'evt-1',
    title: 'Equinox Pilates',
    event_date: '2026-10-03',
    status: 'Submitted',
    location_name: 'San Francisco (Market St)',
    region: 'SF',
    cost_per_person: 15,
    primary_host: 'Leighton Gordon',
    co_hosts: ['Adi', 'Brian T.'],
    notes: 'Morning Pilates stretch session for Bay Area alumni with private studio reservation and smoothies afterwards.',
    workflow_progress_current: 20,
    workflow_progress_total: 15,
    created_at: '2026-07-20T10:00:00Z',
    updated_at: '2026-08-01T12:00:00Z'
  },
  {
    id: 'evt-2',
    title: 'Dolores Park Picnic',
    event_date: '2026-10-08',
    status: 'Planning',
    location_name: 'San Francisco (Mission)',
    region: 'SF',
    cost_per_person: 0,
    primary_host: 'Janice K.',
    co_hosts: ['Leighton Gordon', 'Adi'],
    notes: 'Annual fall outdoor mixer at Mission Dolores Park. Bring blankets, sunblock, and lawn games.',
    workflow_progress_current: 20,
    workflow_progress_total: 14,
    created_at: '2026-07-25T14:00:00Z',
    updated_at: '2026-08-05T09:30:00Z'
  },
  {
    id: 'evt-3',
    title: 'Wine Tasting Napa',
    event_date: '2026-10-19',
    status: 'Planning',
    location_name: 'Napa Valley / SF Pickup',
    region: 'SF',
    cost_per_person: 65,
    primary_host: 'Janice K.',
    co_hosts: ['Tammy Chen'],
    notes: 'Chartered luxury sprinter van from Downtown SF to 2 boutique alumni-owned wineries in Stags Leap.',
    workflow_progress_current: 9,
    workflow_progress_total: 13,
    created_at: '2026-07-15T11:00:00Z',
    updated_at: '2026-07-25T16:45:00Z'
  },
  {
    id: 'evt-4',
    title: 'Quarterly Cafe Meetup',
    event_date: '2026-10-22',
    status: 'Planning',
    location_name: 'San Francisco (SOMA)',
    region: 'SF',
    cost_per_person: 5,
    primary_host: 'Tammy Chen',
    co_hosts: ['Leighton Gordon', 'Adi'],
    notes: 'Casual Thursday morning coffee & tech networking meetup at Sightglass SOMA.',
    workflow_progress_current: 9,
    workflow_progress_total: 13,
    created_at: '2026-07-28T08:00:00Z',
    updated_at: '2026-08-04T15:10:00Z'
  },
  {
    id: 'evt-5',
    title: 'Alumni Volunteer Meeting',
    event_date: '2026-11-15',
    status: 'Planning',
    location_name: 'San Francisco',
    region: 'SF',
    cost_per_person: 0,
    primary_host: 'Tammy Chen',
    co_hosts: ['Brian T.'],
    notes: 'Q4 club committee meeting to review 2027 calendar, volunteer assignments, and campus tie-ins.',
    workflow_progress_current: 0,
    workflow_progress_total: 13,
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-08-01T10:00:00Z'
  },
  {
    id: 'evt-6',
    title: 'Thanksgiving Dinner',
    event_date: '2026-11-26',
    status: 'Idea',
    location_name: 'San Francisco',
    region: 'SF',
    cost_per_person: 45,
    primary_host: 'Janice K.',
    co_hosts: [],
    notes: 'Friendsgiving feast for Bay Area alumni staying in town during Thanksgiving week.',
    workflow_progress_current: 0,
    workflow_progress_total: 10,
    created_at: '2026-08-02T13:00:00Z',
    updated_at: '2026-08-02T13:00:00Z'
  },
  {
    id: 'evt-7',
    title: 'Holiday Party',
    event_date: '2026-12-12',
    status: 'Planning',
    location_name: 'San Francisco (FiDi)',
    region: 'SF',
    cost_per_person: 35,
    primary_host: 'Leighton Gordon',
    co_hosts: ['Adi', 'Janice K.'],
    notes: 'Signature annual Bay Area alumni gala cocktail reception with live jazz and NYU memorabilia raffle.',
    workflow_progress_current: 4,
    workflow_progress_total: 14,
    created_at: '2026-07-10T17:00:00Z',
    updated_at: '2026-08-08T11:20:00Z'
  },
  {
    id: 'evt-8',
    title: 'New Year Mixer',
    event_date: '2027-01-08',
    status: 'Planning',
    location_name: 'San Francisco (Marina)',
    region: 'SF',
    cost_per_person: 15,
    budgeted_subsidy: 200,
    primary_host: 'Janice K.',
    co_hosts: ['Leighton Gordon'],
    notes: 'Kick off 2027 with fellow alumni, new resolution discussions, and welcome new grads relocating to SF.',
    workflow_progress_current: 2,
    workflow_progress_total: 12,
    created_at: '2026-08-05T09:00:00Z',
    updated_at: '2026-08-05T09:00:00Z'
  },
  // Completed Past Events (FY26)
  {
    id: 'evt-9',
    title: 'First Friday Happy Hour',
    event_date: '2025-09-05',
    status: 'Completed',
    location_name: 'San Francisco (FiDi)',
    region: 'SF',
    cost_per_person: 0,
    budgeted_subsidy: 600,
    actual_subsidy: 728.77,
    primary_host: 'Leighton Gordon',
    co_hosts: ['Adi'],
    notes: 'Kickoff happy hour welcoming new alumni to the Bay Area.',
    workflow_progress_current: 14,
    workflow_progress_total: 14,
    created_at: '2025-08-01T10:00:00Z',
    updated_at: '2025-09-06T00:00:00Z'
  },
  {
    id: 'evt-10',
    title: 'San Francisco Ballet',
    event_date: '2025-12-07',
    status: 'Completed',
    location_name: 'War Memorial Opera House (SF)',
    region: 'SF',
    cost_per_person: 45,
    budgeted_subsidy: 300,
    actual_subsidy: 300,
    primary_host: 'Janice K.',
    co_hosts: ['Tammy Chen'],
    notes: 'Nutcracker performance with pre-show champagne reception.',
    workflow_progress_current: 14,
    workflow_progress_total: 14,
    created_at: '2025-10-15T11:00:00Z',
    updated_at: '2025-12-08T00:00:00Z'
  },
  {
    id: 'evt-11',
    title: 'Holiday Party 2025',
    event_date: '2025-12-13',
    status: 'Completed',
    location_name: 'San Francisco (Nob Hill)',
    region: 'SF',
    cost_per_person: 35,
    budgeted_subsidy: 1500,
    actual_subsidy: 1500,
    budget_notes: '**actually ~ $3500 because of unsold tickets',
    primary_host: 'Leighton Gordon',
    co_hosts: ['Janice K.', 'Adi'],
    notes: 'Annual holiday gala with live jazz and alumni toast.',
    workflow_progress_current: 14,
    workflow_progress_total: 14,
    created_at: '2025-10-01T10:00:00Z',
    updated_at: '2025-12-14T00:00:00Z'
  },
  {
    id: 'evt-12',
    title: 'Top Golf Day of Fun',
    event_date: '2026-02-22',
    status: 'Completed',
    location_name: 'San Jose (South Bay)',
    region: 'South Bay',
    cost_per_person: 25,
    budgeted_subsidy: 488.30,
    actual_subsidy: 372.20,
    budget_notes: '**744.40, shared with Stern',
    primary_host: 'David Chen',
    co_hosts: ['Marcus Vance'],
    notes: 'Joint TopGolf tournament shared 50% with Stern alumni.',
    workflow_progress_current: 14,
    workflow_progress_total: 14,
    created_at: '2026-01-05T12:00:00Z',
    updated_at: '2026-02-23T00:00:00Z'
  },
  {
    id: 'evt-13',
    title: 'Etiquette Lunch',
    event_date: '2026-03-21',
    status: 'Completed',
    location_name: 'San Francisco (Union Square)',
    region: 'SF',
    cost_per_person: 30,
    budgeted_subsidy: 400,
    actual_subsidy: 756.92,
    primary_host: 'Tammy Chen',
    co_hosts: ['Priya Sharma'],
    notes: 'Professional business dining and executive etiquette workshop.',
    workflow_progress_current: 14,
    workflow_progress_total: 14,
    created_at: '2026-02-01T09:00:00Z',
    updated_at: '2026-03-22T00:00:00Z'
  },
  {
    id: 'evt-14',
    title: 'Pole Fitness Class at Vertica',
    event_date: '2026-05-09',
    status: 'Completed',
    location_name: 'San Francisco (Mission)',
    region: 'SF',
    cost_per_person: 15,
    budgeted_subsidy: 100,
    actual_subsidy: 100,
    primary_host: 'Priya Sharma',
    co_hosts: [],
    notes: 'Beginner fitness workout workshop for young alumni.',
    workflow_progress_current: 14,
    workflow_progress_total: 14,
    created_at: '2026-04-01T10:00:00Z',
    updated_at: '2026-05-10T00:00:00Z'
  },
  {
    id: 'evt-15',
    title: 'elaichi co visit snacks',
    event_date: '2026-05-16',
    status: 'Completed',
    location_name: 'Berkeley (East Bay)',
    region: 'East Bay',
    cost_per_person: 10,
    budgeted_subsidy: 160,
    actual_subsidy: 160,
    primary_host: 'Adi',
    co_hosts: ['Janice K.'],
    notes: 'Bakery tour and chai tasting mixer in Berkeley.',
    workflow_progress_current: 14,
    workflow_progress_total: 14,
    created_at: '2026-04-10T14:00:00Z',
    updated_at: '2026-05-17T00:00:00Z'
  },
];

export const INITIAL_AWARENESS_EVENTS: AwarenessEvent[] = [
  {
    id: 'awr-1',
    title: 'SF Tech Week Social Event',
    start_date: '2026-10-05',
    end_date: '2026-10-11',
    location: 'San Francisco',
    category: 'Community / Conference',
    is_multi_day: true,
    color_tag: 'emerald',
    notes: 'Massive tech week across SF. High demand for venues, but high density of alumni in town for synergy!'
  },
  {
    id: 'awr-2',
    title: 'SF Tech Week Happy Hour',
    start_date: '2026-10-09',
    end_date: '2026-10-09',
    location: 'San Francisco',
    category: 'Community / Conference',
    is_multi_day: false,
    color_tag: 'emerald',
    notes: 'Community tech happy hour.'
  },
  {
    id: 'awr-3',
    title: 'SOCAP',
    start_date: '2026-10-13',
    end_date: '2026-10-16',
    location: 'San Francisco (Yerba Buena)',
    category: 'Community / Conference',
    is_multi_day: true,
    color_tag: 'emerald',
    notes: 'Social Capital Markets annual conference for impact investing, ESG, and social enterprise leaders.'
  },
  {
    id: 'awr-4',
    title: 'Indigenous Peoples\' Day',
    start_date: '2026-10-12',
    end_date: '2026-10-12',
    location: 'Bay Area / Federal',
    category: 'Civic / Holiday',
    is_multi_day: false,
    color_tag: 'blue',
    notes: 'Long weekend civic holiday.'
  },
  {
    id: 'awr-5',
    title: 'Halloween',
    start_date: '2026-10-31',
    end_date: '2026-10-31',
    location: 'Bay Area',
    category: 'Civic / Holiday',
    is_multi_day: false,
    color_tag: 'amber',
    notes: 'Halloween weekend - avoid scheduling conflicting formal dinners.'
  },
  {
    id: 'awr-6',
    title: 'Christmas',
    start_date: '2026-12-25',
    end_date: '2026-12-25',
    location: 'Global',
    category: 'Civic / Holiday',
    is_multi_day: false,
    color_tag: 'blue',
    notes: 'Winter holiday shutdown.'
  },
  {
    id: 'awr-7',
    title: 'J.P. Morgan Healthcare Conference Jan 11-14',
    start_date: '2027-01-11',
    end_date: '2027-01-14',
    location: 'San Francisco (Union Square)',
    category: 'Community / Conference',
    is_multi_day: true,
    color_tag: 'emerald',
    notes: 'Major global healthcare/biotech conference. High hotel & venue compression in Downtown SF.'
  },
  {
    id: 'awr-8',
    title: 'Lunar New Year',
    start_date: '2027-02-06',
    end_date: '2027-02-06',
    location: 'San Francisco (Chinatown)',
    category: 'Cultural',
    is_multi_day: false,
    color_tag: 'rose',
    notes: 'San Francisco Chinatown festival & parade celebration.'
  },
  {
    id: 'awr-9',
    title: 'Holi',
    start_date: '2027-03-22',
    end_date: '2027-03-22',
    location: 'Bay Area',
    category: 'Cultural',
    is_multi_day: false,
    color_tag: 'purple',
    notes: 'Spring festival of colors.'
  }
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'tsk-1',
    title: 'Submit Dolores Park details (6w warning)',
    assignee: 'Leighton',
    completed: false,
    due_date: '2026-08-27',
    event_id: 'evt-2',
    warning_type: '6w'
  },
  {
    id: 'tsk-2',
    title: 'Follow up on Equinox proposal',
    assignee: 'Leighton',
    completed: false,
    due_date: '2026-08-20',
    event_id: 'evt-1',
    warning_type: 'standard'
  },
  {
    id: 'tsk-3',
    title: 'Draft newsletter copy for Napa trip',
    assignee: 'Leighton',
    completed: false,
    due_date: '2026-09-01',
    event_id: 'evt-3',
    warning_type: 'standard'
  },
  {
    id: 'tsk-4',
    title: 'Draft newsletter tasks details planned',
    assignee: 'Leighton',
    completed: false,
    due_date: '2026-09-10',
    event_id: 'evt-5',
    warning_type: 'standard'
  }
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-1',
    user_name: 'Jan',
    user_avatar_initials: 'J',
    action: 'added new Grad event',
    target: 'Young Alumni Social',
    created_at: '2026-08-10T15:00:00Z',
    relative_time: '1 days ago',
    badge_color: 'bg-emerald-600 text-white'
  },
  {
    id: 'act-2',
    user_name: 'Tammy',
    user_avatar_initials: 'T',
    action: 'updated Wine Tasting Napa status to Planning',
    target: 'Wine Tasting Napa',
    created_at: '2026-07-25T14:30:00Z',
    relative_time: '17 days ago',
    badge_color: 'bg-purple-600 text-white'
  },
  {
    id: 'act-3',
    user_name: 'Adi',
    user_avatar_initials: 'A',
    action: 'edited Quarterly Cafe details',
    target: 'Quarterly Cafe Meetup',
    created_at: '2026-08-04T12:00:00Z',
    relative_time: '7 days ago',
    badge_color: 'bg-purple-600 text-white'
  },
  {
    id: 'act-4',
    user_name: 'Adi',
    user_avatar_initials: 'A',
    action: 'edited Quarterly Cafe details',
    target: 'Quarterly Cafe Meetup',
    created_at: '2026-08-04T11:45:00Z',
    relative_time: '7 days ago',
    badge_color: 'bg-purple-600 text-white'
  },
  {
    id: 'act-5',
    user_name: 'Adi',
    user_avatar_initials: 'A',
    action: 'edited Quarterly Cafe details',
    target: 'Quarterly Cafe Meetup',
    created_at: '2026-08-04T11:30:00Z',
    relative_time: '7 days ago',
    badge_color: 'bg-purple-600 text-white'
  }
];

export const INITIAL_CLUB_LEADERS: ClubLeader[] = [
  {
    id: 'leader-1',
    name: 'Leighton Gordon',
    role: 'Club Co-Lead & Operations Lead',
    email: 'leighton.gordon@alumni.nyu.edu',
    avatar_initials: 'LG',
    badge: 'Club Lead',
    bio: 'Leading club operations, event planning coordination, and 8w/6w lead-time pipeline compliance.',
    assigned_events_count: 3,
    sla_compliance_rate: '100%',
    active_quarter_capacity: '3 / 4 Q4 Planned',
    created_at: '2026-06-01T10:00:00Z',
  },
  {
    id: 'leader-2',
    name: 'Janice K.',
    role: 'VP of Programs & Planning',
    email: 'janice.k@alumni.nyu.edu',
    avatar_initials: 'JK',
    badge: 'VP Programs',
    bio: 'Curating cultural, arts, and alumni dining experiences across the Bay Area.',
    assigned_events_count: 3,
    sla_compliance_rate: '95%',
    active_quarter_capacity: '3 / 3 Q4 Planned',
    created_at: '2026-06-05T11:30:00Z',
  },
  {
    id: 'leader-3',
    name: 'Marcus Vance',
    role: 'Tech & AI Coordinator',
    email: 'marcus.vance@alumni.nyu.edu',
    avatar_initials: 'MV',
    badge: 'Tech Lead',
    bio: 'Spearheading founder roundtables, tech meetups during SF Tech Week, and engineering career circles.',
    assigned_events_count: 2,
    sla_compliance_rate: '100%',
    active_quarter_capacity: '2 / 4 Q4 Planned',
    created_at: '2026-06-10T09:00:00Z',
  },
  {
    id: 'leader-4',
    name: 'Priya Sharma',
    role: 'Young Alumni & Social Chair',
    email: 'priya.sharma@alumni.nyu.edu',
    avatar_initials: 'PS',
    badge: 'Social Chair',
    bio: 'Engaging recent graduates and young alumni with hikes, mixers, social dinners, and welcome mixers.',
    assigned_events_count: 2,
    sla_compliance_rate: '92%',
    active_quarter_capacity: '2 / 3 Q4 Planned',
    created_at: '2026-06-15T14:20:00Z',
  },
  {
    id: 'leader-5',
    name: 'David Chen',
    role: 'Finance & Partnerships Lead',
    email: 'david.chen@alumni.nyu.edu',
    avatar_initials: 'DC',
    badge: 'Finance Lead',
    bio: 'Organizing venture capital dinners, fintech summits during J.P. Morgan week, and sponsor partnerships.',
    assigned_events_count: 1,
    sla_compliance_rate: '98%',
    active_quarter_capacity: '1 / 2 Q4 Planned',
    created_at: '2026-06-20T16:00:00Z',
  },
  {
    id: 'leader-6',
    name: 'Tammy Chen',
    role: 'Mentorship & Networking Lead',
    email: 'tammy.chen@alumni.nyu.edu',
    avatar_initials: 'TC',
    badge: 'Mentorship Lead',
    bio: 'Connecting alumni through roundtables, career mentorship pairings, and networking breakfasts.',
    assigned_events_count: 1,
    sla_compliance_rate: '100%',
    active_quarter_capacity: '1 / 2 Q4 Planned',
    created_at: '2026-07-01T10:00:00Z',
  },
  {
    id: 'leader-7',
    name: 'Adi',
    role: 'Community Outreach Coordinator',
    email: 'adi@alumni.nyu.edu',
    avatar_initials: 'AG',
    badge: 'Community Lead',
    bio: 'Fostering inclusive alumni gatherings, park picnics, volunteering days, and game day watch parties.',
    assigned_events_count: 1,
    sla_compliance_rate: '100%',
    active_quarter_capacity: '1 / 2 Q4 Planned',
    created_at: '2026-07-05T12:00:00Z',
  },
];

export const INITIAL_BUDGET_ITEMS: BudgetItem[] = [
  {
    id: 'bgt-1',
    event_name: 'First Friday Happy Hour',
    date: '2025-09-05',
    budgeted: 600.0,
    actual: 728.77,
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-2',
    event_name: 'First Friday Happy Hour',
    date: '2025-10-03',
    budgeted: 40.0,
    actual: 40.0,
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-3',
    event_name: "Tomorrow's Wine Tasting",
    date: '2025-10-19',
    budgeted: 0.0,
    actual: 267.97,
    notes: 'Paid for past fiscal year',
    is_paid_past_fy: true,
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-4',
    event_name: 'TechCrunch Meet-Up',
    date: '2025-10-28',
    budgeted: 0.0,
    actual: 0.0,
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-5',
    event_name: 'San Francisco Ballet',
    date: '2025-12-07',
    budgeted: 300.0,
    actual: 300.0,
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-6',
    event_name: 'Holiday Party in San Francisco',
    date: '2025-12-13',
    budgeted: 1500.0,
    actual: 1500.0,
    notes: '**actually ~ $3500 because of unsold tickets',
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-7',
    event_name: 'Quarterly Wine Club 1',
    date: '2026-01-03',
    budgeted: 115.0,
    actual: 137.33,
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-8',
    event_name: 'Equinox Palo Alto',
    date: '2026-01-10',
    budgeted: -160.0,
    actual: -90.0,
    notes: 'Revenue surplus from partner ticket sales',
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-9',
    event_name: 'Warriors vs Knicks',
    date: '2026-01-15',
    budgeted: 0.0,
    actual: 0.0,
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-10',
    event_name: 'Equinox SF',
    date: '2026-01-17',
    budgeted: -160.0,
    actual: -115.0,
    notes: 'Ticket sales surplus',
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-11',
    event_name: 'Top Golf Day of Fun',
    date: '2026-02-22',
    budgeted: 488.3,
    actual: 372.2,
    notes: '**744.40, shared with Stern',
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-12',
    event_name: 'Flow State - Water Energy Sound Bath',
    date: '2026-02-28',
    budgeted: 100.0,
    actual: 100.0,
    notes: '**actually $980 because of unsold tickets',
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-13',
    event_name: 'Elephant Seal Walk',
    date: '2026-03-14',
    budgeted: 0.0,
    actual: 0.0,
    is_cancelled: true,
    notes: 'Cancelled due to severe rain',
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-14',
    event_name: 'Etiquette Lunch',
    date: '2026-03-21',
    budgeted: 400.0,
    actual: 756.92,
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-15',
    event_name: 'Quarterly Wine Club 2',
    date: '2026-03-22',
    budgeted: 137.33,
    actual: 128.7,
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-16',
    event_name: 'Pole Fitness Class at Vertica',
    date: '2026-05-09',
    budgeted: 100.0,
    actual: 100.0,
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-17',
    event_name: 'elaichi co visit snacks (estimate)',
    date: '2026-05-16',
    budgeted: 160.0,
    actual: 160.0,
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-18',
    event_name: 'Asian Art Museum',
    date: '2026-05-21',
    budgeted: 60.0,
    actual: null,
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-19',
    event_name: 'Quarterly Wine Club 3',
    date: '2026-06-20',
    budgeted: 137.33,
    actual: null,
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-20',
    event_name: "Stonefruit Picking at Andy's Orchard",
    date: '2026-08-15',
    budgeted: 125.0,
    actual: 0.0,
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-21',
    event_name: 'Quarterly Coffee Meet-up at Stray Dog',
    date: '2026-08-29',
    budgeted: 180.0,
    actual: null,
    fiscal_year: 'FY26',
  },
  {
    id: 'bgt-22',
    event_name: 'Dolores Picnic',
    date: '2026-08-22',
    budgeted: 100.0,
    actual: null,
    fiscal_year: 'FY26',
  },
  // Upcoming FY27
  {
    id: 'bgt-23',
    event_id: 'evt-1',
    event_name: 'SF Tech Week Happy Hour',
    date: '2026-10-09',
    budgeted: 250.0,
    actual: null,
    notes: 'Subsidize appetizers and NYU banner at bar',
    fiscal_year: 'FY27',
  },
  {
    id: 'bgt-24',
    event_id: 'evt-2',
    event_name: 'Dolores Park Picnic',
    date: '2026-10-08',
    budgeted: 150.0,
    actual: null,
    notes: 'Catering, picnic blankets & lawn games',
    fiscal_year: 'FY27',
  },
  {
    id: 'bgt-25',
    event_id: 'evt-7',
    event_name: 'Annual Alumni Holiday Gala',
    date: '2026-12-12',
    budgeted: 1200.0,
    actual: null,
    notes: 'Venue deposit subsidy & live band',
    fiscal_year: 'FY27',
  },
  {
    id: 'bgt-26',
    event_id: 'evt-8',
    event_name: 'New Year Welcome Mixer',
    date: '2027-01-08',
    budgeted: 200.0,
    actual: null,
    fiscal_year: 'FY27',
  },
];

